import type { Article } from '../../types';

const article: Article = {
  id: 49,
  title: 'Why AI sometimes "makes things up": hallucinations and how to verify it',
  metaTitle: 'AI Hallucinations: Why AI Invents and How to Check | DigitiNexus',
  slug: 'ai-hallucinations',
  locale: 'en',
  altLocaleSlug: 'allucinazioni-ai',
  metaDescription:
    'What AI hallucinations are, why they happen, and how to verify AI answers before you use them in your work.',
  capsule:
    'AI hallucinations are answers that sound right but are not: the model predicts likely words, not the truth. It fills gaps with confident text that can be invented or wrong. To use AI at work, always verify the facts and the sources before you rely on them.',
  keywordPrimary: 'AI hallucinations',
  keywordsSecondary: ['why AI gets things wrong', 'verify AI answers', 'AI reliability'],
  cluster: 'c7',
  intent: 'I·TOFU',
  authorId: 'nicola-palummo',
  publishDate: '2026-07-03',
  updatedDate: '2026-07-03',
  status: 'published',
  cover: {
    src: '/blog/covers/allucinazioni-ai-en.webp',
    alt: 'AI hallucinations: why an AI model sometimes invents answers that sound plausible but are wrong',
  },
  body: [
    { type: 'h2', text: 'What are AI hallucinations?' },
    {
      type: 'p',
      lead: true,
      text: 'AI hallucinations are answers that look correct but are not: the model produces a plausible piece of information, written in a confident tone, that is actually invented or wrong. This is not an occasional glitch, it is expected behavior baked into how the technology works. That is why you should always treat them as possible.',
    },
    {
      type: 'callout',
      variant: 'info',
      text: '**Hallucination (AI):** an answer generated by an AI model that looks believable and coherent but contains false, inaccurate, or invented information. The problem is not the error itself, but the fact that it arrives with the same confidence as a correct answer, which makes it hard to spot at a glance.',
    },
    {
      type: 'p',
      text: 'The word "hallucination" fits for exactly that reason: the AI does not "see" that it is wrong. It cites a statute that does not exist, attributes a quote to someone who never said it, hands you a precise date that is simply false. And it does this with the same ease it would use to give you a correct answer, with no signal of uncertainty at all.',
    },
    {
      type: 'p',
      text: 'It helps to separate two things. An AI can be wrong because it never had the information, or because it had it and blended it badly. Either way the result for you is identical: convincing text you cannot trust to be true. That is where the real risk on the job begins, because a wrong figure taken at face value can be expensive.',
    },

    { type: 'h2', text: 'Why do AI hallucinations happen?' },
    {
      type: 'p',
      lead: true,
      text: 'They happen because a language model does not look up a database of facts: it predicts the most likely word after the previous ones, one at a time. It generates statistically plausible sentences, not verified ones. When the right fact does not stand out strongly in the training data, the model completes the sentence anyway, with something that "sounds" right but is not.',
    },
    {
      type: 'p',
      text: 'This is the difference between recalling and computing probability. A database answers "not found" to a question it does not know. A language model is built to always produce a smooth continuation of the text: its goal during training is to guess the next word, not to tell the truth. Truth and plausibility often coincide, but not always, and when they split apart the hallucination appears.',
    },
    {
      type: 'p',
      text: 'Some situations raise the risk. Questions about very specific or niche facts, about recent events the model never saw, about exact numbers and quotes. Even a vague question, or one that assumes a false premise, pushes the model to "invent" just to play along. Understanding this mechanism is the foundation of everything: the AI does not lie, it completes. Techniques like [RAG](/en/blog/rag-ai-on-your-company-data) exist to give it real text to start from instead of memory alone.',
    },

    { type: 'h2', text: 'Where are AI hallucinations most dangerous?' },
    {
      type: 'p',
      lead: true,
      text: 'The risk is not the same everywhere: it depends on what the error costs. In legal, tax, medical, or financial work, a wrong fact taken at face value can turn into real harm, a missed deadline, or bad advice to a client. In creative or brainstorming uses, an inaccuracy is far less serious, sometimes irrelevant.',
    },
    {
      type: 'p',
      text: 'The most delicate case is professionals working with regulated information. An attorney asking the AI for the details of a court ruling, a CPA having it summarize a tax rule, a financial advisor quoting a percentage: if the AI hallucinates and nobody checks, the error reaches the client under the professional\'s name. The point is not to avoid AI, it is to never hand it the responsibility for review. We come back to this in AI for professional firms.',
    },
    {
      type: 'p',
      text: 'A second area to handle with care is public-facing content. A page on your site, a post, an automated reply to a customer: if it contains an invented fact, the error becomes visible and public, and it chips away at the trust you built. The practical rule is simple: the further an AI answer travels from you toward the outside world, the more it has to be checked before it goes out.',
    },
    {
      type: 'list',
      items: [
        '**High risk:** legal and tax advice, medical data, figures and quotes in official documents, communications to clients.',
        '**Medium risk:** content drafts, document summaries, preliminary research you still need to refine by hand.',
        '**Low risk:** ideas, alternative headlines, brainstorming, rewrites of text you already wrote yourself.',
      ],
    },

    { type: 'h2', text: 'How do you reduce and verify AI hallucinations?' },
    {
      type: 'p',
      lead: true,
      text: 'Hallucinations never disappear entirely, but a few habits cut them sharply: give the AI the right sources instead of trusting its memory, write clear requests, always ask where a piece of information comes from, and keep the final word in human hands. These are simple steps that move reliability in a real way.',
    },
    {
      type: 'p',
      text: 'The first fix is at the root: give the model real text to ground itself in. When you connect the AI to your documents with a [RAG](/en/blog/rag-ai-on-your-company-data) system, answers start from a concrete source and the tendency to invent drops, because the model no longer has to fill gaps from memory. It is the difference between asking "what do you think" and asking "read this document and answer".',
    },
    {
      type: 'p',
      text: 'The second fix is in how you ask. A vague request leaves room for invention; a precise request, with the context and the format you need, reduces ambiguity. Asking explicitly "if you are not sure, tell me instead of guessing" often changes the quality of the answer. You can see how to set up strong requests in [effective prompts for work](/en/blog/effective-prompts-for-work).',
    },
    {
      type: 'list',
      ordered: true,
      items: [
        '**Ask for sources:** always ask where a piece of information comes from, and check that the source actually exists and says what the model claims.',
        '**Verify the "hard" facts:** numbers, dates, names, quotes, and legal references need a manual recheck, because they are what the model gets wrong most often.',
        '**Distrust the confident tone:** how confidently the AI answers is no sign of correctness; a hallucination sounds just as convincing as a real fact.',
        '**Cross-check sources:** for anything important, confirm the fact against an independent, reliable source before you use it.',
      ],
    },
    {
      type: 'callout',
      variant: 'tip',
      text: 'Use AI like a brilliant but junior teammate: great for producing a fast first draft, never the final word on a fact. You stay the reviewer, especially for anything that goes out to a client.',
    },

    { type: 'h2', text: 'What is the golden rule for professionals?' },
    {
      type: 'p',
      lead: true,
      text: 'There is just one rule: never publish or deliver an AI answer without verifying it first. AI is a powerful tool for speeding up your work, not an oracle you can hand the responsibility to. The final check stays yours, and with it the trust your client places in you.',
    },
    {
      type: 'p',
      text: 'In practice: AI takes you from a blank page to a draft in minutes, and that is a huge gain. But between the draft and what you sign with your name there is one step you cannot skip, the verification. Skipping that step is not saving time, it is shifting the risk onto the client. Respecting it lets you use AI for what it is genuinely good at: getting you started faster.',
    },
    {
      type: 'p',
      text: 'This matters even more for anyone working with regulated or sensitive information. A well-built AI assistant, fed your own documents and used with method, saves you hours without exposing you. You can see how to bring it into your work the right way in [AI for your business](/en/blog/ai-for-businesses), where we walk through concrete uses and how to hold speed and reliability together.',
    },
    {
      type: 'cta',
      text: 'Want to use AI in your work without exposing yourself to errors? We build an assistant fed by your real data, with human control where it matters.',
      label: 'Let\'s talk',
      href: 'https://calendly.com/digitinexus/30min',
    },
  ],
  faq: [
    {
      q: 'Does AI say false things on purpose?',
      a: 'No, there is no intent. A language model does not "know" it is wrong: it predicts the most likely word after the previous ones, and sometimes the most plausible sequence does not match the truth. It does not lie, it completes the text. That is why the error arrives in the same confident tone as a correct answer.',
    },
    {
      q: 'Do newer models hallucinate less?',
      a: 'In general, more recent models get things wrong less often and handle uncertainty better, but the problem does not vanish: it comes from how the technology works, not from a defect you can patch. Even with the best models, verification stays necessary, especially for numbers, dates, quotes, and regulated information.',
    },
    {
      q: 'How do I verify an answer quickly?',
      a: 'Focus on the "hard" facts: numbers, dates, names, quotes, and legal references, because they are what AI gets wrong most often. Always ask for the source and check that it exists and really says what the model claims. For anything important, confirm it against an independent, reliable source.',
    },
    {
      q: 'Can I trust AI for my work?',
      a: 'Yes, as a tool to speed things up, not as a source of truth. Use it for drafts, summaries, and ideas, while keeping human control over the final word. The further an answer travels toward a client, the more it has to be checked. Connecting it to your documents with a RAG system sharply reduces invented answers.',
    },
    {
      q: 'Why does AI sound so confident when it is wrong?',
      a: 'Because confidence and correctness are unrelated for a language model. It is built to produce fluent, well-formed text, so a hallucination reads as smoothly as a fact. The tone tells you nothing about accuracy, which is exactly why a confident answer is not a reason to skip the check.',
    },
  ],
  internalLinks: [
    { slug: 'ai-for-businesses', anchor: 'AI for your business' },
    { slug: 'rag-ai-on-your-company-data', anchor: 'RAG: the AI that answers with your data' },
    { slug: 'effective-prompts-for-work', anchor: 'Effective prompts for work' },
  ],
  sources: [],
};

export default article;
