import type { Article } from '../../types';

const article: Article = {
  id: 19,
  title: 'GEO: How to Get Cited by ChatGPT, Gemini, and AI Overviews',
  metaTitle: 'GEO: Get Cited by ChatGPT & AI Overviews | DigitiNexus',
  slug: 'generative-engine-optimization',
  locale: 'en',
  altLocaleSlug: 'geo-generative-engine-optimization',
  metaDescription:
    'A guide to Generative Engine Optimization: what GEO is and how to structure content so ChatGPT, Gemini, Perplexity, and Google cite your business.',
  capsule:
    'GEO (Generative Engine Optimization) is the set of techniques that get your business cited inside AI answers like ChatGPT, Gemini, Perplexity, and Google AI Overviews. It is not about ranking higher. It is about becoming the source the model quotes, built on structured content, verifiable data, and real authority.',
  keywordPrimary: 'generative engine optimization',
  keywordsSecondary: ['GEO', 'get cited by ChatGPT', 'AI Overview optimization'],
  cluster: 'c3',
  isPillar: true,
  intent: 'I·TOFU',
  authorId: 'filippo-gentili',
  publishDate: '2026-06-03',
  updatedDate: '2026-06-03',
  status: 'published',
  cover: {
    src: '/blog/covers/geo-generative-engine-optimization-en.webp',
    alt: 'GEO Generative Engine Optimization: how to get cited by ChatGPT, Gemini, and Google AI Overviews',
  },
  body: [
    { type: 'h2', text: 'What is GEO?' },
    {
      type: 'p',
      lead: true,
      text: 'GEO (Generative Engine Optimization) is the set of techniques that make your business show up in answers generated by AI: ChatGPT, Gemini, Perplexity, and Google AI Overviews. The goal is not to climb a ranking. It is to become the source the model cites when it answers.',
    },
    {
      type: 'p',
      text: 'The difference from SEO is sharp. SEO works to rank a page so you earn **a click**; GEO works to make your page **the cited source** inside the AI answer, even when the user never clicks at all. The unit of measurement changes: no longer the position, but the citation.',
    },
    {
      type: 'p',
      text: 'One technical detail explains everything else. Generative AI never cites a whole page: it extracts and rewrites *a single passage*. That is why GEO thinks in fragments. A plumbing company in Austin that wants to show up when someone asks ChatGPT "how much does it cost to remodel a bathroom" needs one short, self-contained sentence on the page that answers exactly that question.',
    },
    {
      type: 'p',
      text: 'In practice GEO is SEO with one extra discipline: writing so that every paragraph can be extracted, understood, and repeated by a machine without the surrounding context. The sections below cover why it matters now, how to do it, and what is just noise.',
    },

    { type: 'h2', text: 'Why does GEO matter right now?' },
    {
      type: 'p',
      lead: true,
      text: 'It matters because AI answers now sit on top of the search results, and they change how people click. When Google shows an AI summary, users click a traditional result in only **8% of visits**, versus **15%** when no summary appears (Pew Research Center, 2025). The page you rank on is being read less, even at position one.',
    },
    {
      type: 'p',
      text: 'The bigger pattern behind that: the majority of US Google searches now end without any click to the open web. People get the answer on the results page and move on. Translated: even if you rank first, a large share of that traffic no longer reaches your site.',
    },
    {
      type: 'p',
      text: 'The effect on clicks is measurable. When an AI Overview appears, the click-through rate of the top organic result drops sharply. Position one is worth less than it used to be. If you are not *inside* the AI answer, then for those users your business does not exist, even if you technically sit at the top of Google.',
    },
    {
      type: 'p',
      text: 'Coverage varies by sector. AI Overviews show up less often on sensitive topics like health, finance, and legal, where Google is more cautious because a wrong answer is costly. That is a useful signal: where AI Overviews are rare, classic SEO keeps more weight; where they dominate, GEO becomes the priority. Check how often they appear for your own queries before deciding how much to invest.',
    },
    {
      type: 'p',
      text: 'The practical consequence is a change of goal. Being first is no longer enough: you need to be the source the AI summarizes at the top of the page. It is new ground, still lightly contested by small businesses, and therefore an opening: whoever structures content well now starts ahead. The full map of AI Overviews is in the [guide to Google AI Overviews](/en/blog/google-ai-overviews).',
    },

    { type: 'h2', text: 'Do GEO and SEO conflict?' },
    {
      type: 'p',
      lead: true,
      text: 'No, they are complementary: the large majority of sources cited by AI come from the organic top 10. To be cited, you first have to rank well. SEO does not disappear: it becomes the ticket in.',
    },
    {
      type: 'p',
      text: 'The mechanism has two stages. SEO gets you into the pool of candidate sources, the top-10 pages the model draws from. GEO decides whether, among those, the AI picks you: that depends on how clearly, quotably, and reliably your page answers the question. Skip the first stage and the second is useless.',
    },
    {
      type: 'p',
      text: 'There is a hidden upside. GEO optimizations usually improve SEO too: answering a question immediately, structuring answers well, and citing sources makes the page more useful for the humans who do click. You are not trading away the leftover traffic for a citation: you are raising quality for both audiences, people and models.',
    },
    {
      type: 'p',
      text: 'That is why it makes no sense to choose between them. A solid technical structure, content that answers real questions, and genuine authority serve both. What stays central about classic SEO in 2026 is covered in the [guide to SEO in 2026](/en/blog/seo-in-2026): it is the foundation GEO builds on.',
    },

    { type: 'h2', text: 'How do you write content that AI cites?' },
    {
      type: 'p',
      lead: true,
      text: 'You write it by answering the question immediately, with verifiable data and cited sources. The academic study by **Aggarwal et al. (KDD 2024)** shows that techniques like citing sources, adding quotations, and including statistics can boost visibility in generative engines **by up to 40%** ([arXiv](https://arxiv.org/abs/2311.09735)).',
    },
    {
      type: 'p',
      text: 'The guiding principle is one: AI cites a *passage*, not the whole page. So every section has to contain a short, self-contained answer that makes sense even when pulled out on its own. That is the capsule method: put the answer up front (front-loading), then develop it. This article is written that way, so it is an example of itself.',
    },
    {
      type: 'list',
      items: [
        '**Answer capsule up front:** 40–75 words that directly answer the question in the heading, understandable out of context. This is the fragment the AI extracts and rewrites.',
        '**Answer-first:** every H2 is a question, and the first sentence under it is already the answer, not the setup to the answer.',
        '**One sourced data point per section:** dated numbers and percentages with a link to the source, not adjectives. Quotable statistics raise the odds of being picked up.',
        '**Quotes and citations:** one authoritative sentence in quotation marks gives the model ready-made material to repeat.',
        '**Defined entities:** when you name a concept, define it right away in a self-contained sentence, before you use it.',
        '**Adjacent questions in the same article:** cover several related questions so the page becomes a source for many queries.',
      ],
    },
    {
      type: 'p',
      text: 'A concrete example. The question "how long does it take to build a website" is answered badly with three paragraphs of preamble and well with one tight sentence up front ("A custom brochure site takes 1–4 weeks, depending on pages and content"), followed by the detail. The first version does not get extracted; the second does, because it is a complete capsule the model can repeat without cutting anything.',
    },
    {
      type: 'callout',
      variant: 'tip',
      text: 'Quick test: copy one of your paragraphs, paste it alone into a chat, and ask yourself "does this answer a specific question, without the surrounding context?". If the answer is no, rewrite it as a capsule.',
    },
    {
      type: 'p',
      text: 'The full method, with ready-made capsule examples, is in the [guide to AI-citable content](/en/blog/ai-citable-content-the-capsule-method).',
    },

    { type: 'h2', text: 'Which schema markup helps AI?' },
    {
      type: 'p',
      lead: true,
      text: '**Article**, **FAQPage**, and **Person** in JSON-LD help most: they make the content readable in a structured way. Marking questions and answers with FAQPage and the article with Article helps generative engines isolate and extract the right passages, improving the odds your content gets reused in answers.',
    },
    {
      type: 'p',
      text: '**Schema markup** is code invisible to the reader that describes the content to search engines: who the author is, what the page is about, what the questions and answers are. It does not improve the writing, but it removes ambiguity: it tells the AI explicitly "this is a FAQ, this is the answer, this is the author". The less the AI has to guess, the more confidently it cites you.',
    },
    {
      type: 'table',
      caption: 'Schema markup useful for GEO',
      headers: ['Schema', 'What it does', 'Effect on citations'],
      rows: [
        ['FAQPage', 'Marks up questions and answers', 'Helps extraction of individual Q&As'],
        ['Article + FAQPage + HowTo', 'Article, FAQ, and steps together', 'Covers more extractable formats on one page'],
        ['Person / Author', 'Identifies and links the author', 'Strengthens authority and E-E-A-T'],
      ],
    },
    {
      type: 'p',
      text: 'Practical JSON-LD examples you can paste into a page are in the [guide to schema markup for AI](/en/blog/schema-markup-for-ai).',
    },

    { type: 'h2', text: 'How much do author and authority (E-E-A-T) matter?' },
    {
      type: 'p',
      lead: true,
      text: 'They matter a lot: AI favors recognizable, trustworthy sources. E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) is the framework Google uses to judge the quality of who publishes. Identical content, signed by a credible author, starts ahead.',
    },
    {
      type: 'p',
      text: 'The link to GEO is direct. Models learn to trust the same sources Google treats as authoritative, and those end up in the top-10 pool the citations are drawn from. Three concrete levers: a bylined author with a verifiable public profile; mentions and links from independent third-party sources; a consistent entity, meaning the same name, logo, and description everywhere the brand appears.',
    },
    {
      type: 'callout',
      variant: 'tip',
      text: 'Link every article to a real author page (photo, bio, role, expertise) and mark it up with Person schema. It is the simplest signal to send and one of the most neglected by small businesses.',
    },
    {
      type: 'p',
      text: 'How to build and signal authority in practice is laid out step by step in [E-E-A-T and author authority](/en/blog/e-e-a-t-and-author-authority).',
    },

    { type: 'h2', text: 'Do you need an llms.txt file to get cited?' },
    {
      type: 'p',
      lead: true,
      text: 'Today, not really. It is a low-cost file with no proof of real impact. **Google has stated that none of its AI systems use or support it**, and real-world usage is close to zero: studies that have looked at how often AI bots actually read the file found it is almost never touched. It is a detail, not a strategy.',
    },
    {
      type: 'p',
      text: 'Adding it does no harm and takes a few minutes, so it is not "wrong". But spending an hour on llms.txt instead of an hour on citable content and schema markup is a bad trade. The full verdict, with current data, is in the [guide on llms.txt](/en/blog/does-llms-txt-actually-matter).',
    },

    { type: 'h2', text: 'How do I know if AI is citing me?' },
    {
      type: 'p',
      lead: true,
      text: 'The most direct way is qualitative: ask the AIs the questions your customers typically ask, and see whether you show up among the sources. Open ChatGPT, Gemini, and Perplexity, run the 10–15 real questions from your field, and note who gets cited. That is the starting point, before any tool.',
    },
    {
      type: 'p',
      text: 'Keep two things in mind. First: AI answers vary over time and between engines, so you need periodic checks, not a single snapshot. Second: AI citation-monitoring tools exist that automate these checks, but the judgment stays qualitative. What counts is the trend over time: do you show up more often, on more questions, across more engines?',
    },
    {
      type: 'list',
      ordered: true,
      items: [
        'List the 10–15 real questions customers ask before they buy.',
        'Ask them to the major AIs and note whether and where you are cited.',
        'Record which questions show competitors instead of you.',
        'Create or improve answer capsules on exactly those questions.',
        'Repeat the check after a few weeks and compare.',
      ],
    },

    { type: 'h2', text: 'Where do you start with GEO?' },
    {
      type: 'p',
      lead: true,
      text: 'Start with the pages that already rank. Since most AI citations come from the top 10, take the content Google already rewards and rewrite it with answer capsules up front and sourced data. It is the fastest way to turn rankings you have into citations you do not have yet.',
    },
    {
      type: 'p',
      text: 'GEO is not a project separate from your site: it is how you write and structure every page. So it pays to start from a clean technical base, with schema markup and content built to be cited, rather than chasing optimizations after the fact. For the SEO context that serves as the foundation, the [guide to SEO in 2026](/en/blog/seo-in-2026) stays useful.',
    },
    {
      type: 'list',
      ordered: true,
      items: [
        '**Solid SEO base:** clean structure and pages able to reach the top 10.',
        '**Citable content:** answer capsules up front, one sourced data point per section.',
        '**Schema markup:** Article, FAQPage, and Person in JSON-LD on every key page.',
        '**Authority:** a bylined author, a consistent entity, mentions from third-party sources.',
        '**Monitoring:** periodically ask customer questions to the AIs and adjust.',
      ],
    },
    {
      type: 'cta',
      text: 'Want a website that is ready to be found on Google and cited by AI? We build it schema-ready, in 1–4 weeks.',
      label: "Let's talk",
      href: 'https://calendly.com/digitinexus/30min',
    },
  ],
  faq: [
    {
      q: 'Are GEO and SEO the same thing?',
      a: 'No. SEO ranks a page to earn clicks; GEO gets it cited inside AI answers. They are complementary: most AI citations come from pages already in the top 10, so you build them together, not as alternatives.',
    },
    {
      q: 'How do I know if AI is citing me?',
      a: 'Ask ChatGPT, Gemini, and Perplexity the real questions your customers ask and see whether you appear among the sources. It is a qualitative check: answers shift over time and between engines, so repeat it regularly and watch the trend.',
    },
    {
      q: 'How long does GEO take to show results?',
      a: 'It is not instant. Like SEO, it needs content published consistently, authority that grows, and a consistent entity. GEO speeds up once you already have a solid base of well-ranked, well-structured pages the AI can draw from.',
    },
    {
      q: 'Do you need a blog to do GEO?',
      a: 'It helps a lot. A blog gives you the pages to answer real customer questions with data and sources: exactly the material AI cites. Without content to quote, schema markup and technical files alone are not enough to appear in answers.',
    },
    {
      q: 'Do I have to create an llms.txt file to get cited?',
      a: 'Not today. Google has stated that none of its AI systems use llms.txt, and real-world bot usage is near zero. Adding it is cheap and harmless, but it is not a strategy: invest in citable content and schema markup instead.',
    },
  ],
  internalLinks: [
    { slug: 'google-ai-overviews', anchor: 'Google AI Overviews' },
    { slug: 'schema-markup-for-ai', anchor: 'Schema markup for AI' },
    { slug: 'e-e-a-t-and-author-authority', anchor: 'E-E-A-T and author authority' },
    { slug: 'ai-citable-content-the-capsule-method', anchor: 'AI-citable content: the capsule method' },
    { slug: 'does-llms-txt-actually-matter', anchor: 'Does llms.txt actually matter?' },
    { slug: 'seo-in-2026', anchor: 'SEO in 2026' },
  ],
  sources: [
    { label: 'Aggarwal et al., "GEO: Generative Engine Optimization", KDD 2024 (arXiv)', url: 'https://arxiv.org/abs/2311.09735' },
    { label: 'Pew Research Center — Google users are less likely to click when an AI summary appears (2025)', url: 'https://www.pewresearch.org/short-reads/2025/07/22/google-users-are-less-likely-to-click-on-links-when-an-ai-summary-appears-in-the-results/' },
    { label: 'Ahrefs — AI Overviews are correlated with a lower CTR for the top-ranking page', url: 'https://ahrefs.com/blog/ai-overviews-reduce-clicks/' },
    { label: 'SparkToro — 58.5% of US Google searches ended in zero clicks (2024)', url: 'https://sparktoro.com/blog/2024-zero-click-search-study-for-every-1000-us-google-searches-only-374-clicks-go-to-the-open-web-in-the-eu-its-360/' },
    { label: 'Ahrefs — 97% of llms.txt files are never read (137K-site study)', url: 'https://ahrefs.com/blog/llmstxt-study/' },
  ],
};

export default article;
